INFO:root:New session ––– 2018-11-19 16:17:14.487152 ––– New session
INFO:root:New session ––– 2018-11-19 16:18:03.501923 ––– New session
INFO:root:New session ––– 2018-11-19 16:19:32.156604 ––– New session
INFO:root:New session ––– 2018-12-04 14:54:28.860684 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:54:42.769045 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:54:53.140920 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:55:05.003018 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:55:21.511894 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:55:29.937007 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:55:43.082590 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 14:55:44.360613 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 307-167-365
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 14:55:53] "GET /api/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 14:55:53] "GET /api/swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 14:55:53] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 14:56:11] "GET /swaggerui/bower/swagger-ui/dist/images/throbber.gif HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 14:56:23] "POST /api/users/login HTTP/1.1" 401 -
INFO:root:New session ––– 2018-12-04 14:57:01.014883 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:57:06.548721 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:57:59.735456 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:59:09.508287 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 14:59:20.196556 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:01:43.828247 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:01:57.913639 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:06:14.848276 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:12:15.694549 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:12:25.406019 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:17:53.084956 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:21:45.993484 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:22:28.738242 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:25:29.470391 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:25:38.148789 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:26:54.755527 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:29:32.773889 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:30:10.622108 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:52:06.859671 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:52:14.309342 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:52:22.030654 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:53:15.270147 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:53:32.858778 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:54:33.412921 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:55:46.074962 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:55:51.662292 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 15:55:55.535251 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:04:48.644810 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:09:05.527325 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:09:54.531695 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:10:00.078844 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:10:05.511081 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:10:28.305168 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:11:48.229027 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:29:01.585267 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:30:38.334057 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:30:53.419142 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:31:30.925025 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:33:21.489194 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:33:35.991525 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:43:33.757936 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:45:40.915025 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 16:57:23.539074 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 16:57:24.626431 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:root:New session ––– 2018-12-04 17:00:48.192072 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:00:57.489988 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:01:46.328415 ––– New session
INFO:root:New session ––– 2018-12-04 17:02:16.328731 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:03:00.577243 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:03:35.362530 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:03:42.081622 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:03:47] "GET /api/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:03:48] "GET /api/swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:03:48] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:04:03] "GET /swaggerui/bower/swagger-ui/dist/images/throbber.gif HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:04:11] "POST /api/users/login HTTP/1.1" 401 -
INFO:root:New session ––– 2018-12-04 17:04:53.065875 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:05:06.982351 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:06:45.029937 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:07:17.519859 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:werkzeug: * Detected change in '/Users/jorgevazquez/Documents/wt_test/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:10:10.945662 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:werkzeug: * Detected change in '/Users/jorgevazquez/Documents/wt_test/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:21:05.248583 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:werkzeug: * Detected change in '/Users/jorgevazquez/Documents/wt_test/config.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:24:25.239646 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:werkzeug: * Detected change in '/Users/jorgevazquez/Documents/wt_test/app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:24:56.419741 ––– New session
INFO:root:New session ––– 2018-12-04 17:25:52.234453 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:25:53.484882 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:root:New session ––– 2018-12-04 17:26:13.836675 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:26:18.618371 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:30:35.395786 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:30:36.560455 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:30:46] "GET /api/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:30:47] "GET /api/swagger.json HTTP/1.1" 200 -
ERROR:api.restplus:An unhandled exception occurred.
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "user" does not exist
LINE 2: FROM "user" 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jorgevazquez/Documents/wt_test/api/users/users.py", line 81, in post
    if verify_password(email, password):
  File "/Users/jorgevazquez/Documents/wt_test/api/users/users.py", line 225, in verify_password
    user = User.query.filter_by(email=email_or_token).first()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2695, in first
    ret = list(self[0:1])
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2487, in __getitem__
    return list(res)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "user" does not exist
LINE 2: FROM "user" 
             ^
 [SQL: 'SELECT "user".id AS user_id, "user".created AS user_created, "user".updated AS user_updated, "user".email AS user_email, "user".enrollment AS user_enrollment, "user".password_hash AS user_password_hash, "user".active AS user_active, "user".first_name AS user_first_name, "user".last_name AS user_last_name, "user".role AS user_role \nFROM "user" \nWHERE "user".email = %(email_1)s \n LIMIT %(param_1)s'] [parameters: {'email_1': 'admin@admin.com', 'param_1': 1}]
ERROR:api.restplus:An unhandled exception occurred.
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "user" does not exist
LINE 2: FROM "user" 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_restplus/api.py", line 536, in error_router
    return original_handler(e)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jorgevazquez/Documents/wt_test/api/users/users.py", line 81, in post
    if verify_password(email, password):
  File "/Users/jorgevazquez/Documents/wt_test/api/users/users.py", line 225, in verify_password
    user = User.query.filter_by(email=email_or_token).first()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2695, in first
    ret = list(self[0:1])
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2487, in __getitem__
    return list(res)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "user" does not exist
LINE 2: FROM "user" 
             ^
 [SQL: 'SELECT "user".id AS user_id, "user".created AS user_created, "user".updated AS user_updated, "user".email AS user_email, "user".enrollment AS user_enrollment, "user".password_hash AS user_password_hash, "user".active AS user_active, "user".first_name AS user_first_name, "user".last_name AS user_last_name, "user".role AS user_role \nFROM "user" \nWHERE "user".email = %(email_1)s \n LIMIT %(param_1)s'] [parameters: {'email_1': 'admin@admin.com', 'param_1': 1}]
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:30:59] "POST /api/users/login HTTP/1.1" 500 -
INFO:root:New session ––– 2018-12-04 17:31:19.746728 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:31:27.829600 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:root:New session ––– 2018-12-04 17:32:15.931599 ––– New session
INFO:engineio:Server initialized for gevent.
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:New session ––– 2018-12-04 17:32:17.190235 ––– New session
INFO:engineio:Server initialized for gevent.
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: 252-563-367
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:32:17] "GET /api/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:32:18] "GET /api/swagger.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Dec/2018 17:32:32] "POST /api/users/login HTTP/1.1" 401 -
